### ISSUE TITLE
./timberborn_linux_bepinex.sh: 63: [[: not found

### ISSUE THREAD

**Issue by MarkKocherovsky** [GinFuyou/Timberborn-GinFuyou#1]
Hi, I'm trying to run bepinex; I've followed the steps in the readme, and I'm getting this error in the log:

```
[original command]: /home/<me>/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1062090 -- ./timberborn_linux_bepinex.sh (it will be discarded)
arguments (0 is the base command):
 ./timberborn_linux_bepinex.sh
./timberborn_linux_bepinex.sh: 63: [[: not found
 1: /home/<me>/.steam/debian-installation/ubuntu12_32/reaper
./timberborn_linux_bepinex.sh: 63: [[: not found
 2: SteamLaunch
./timberborn_linux_bepinex.sh: 63: [[: not found
 3: AppId=1062090
./timberborn_linux_bepinex.sh: 63: [[: not found
 4: --
./timberborn_linux_bepinex.sh: 63: [[: not found
 5: /home/<me>/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper
./timberborn_linux_bepinex.sh: 63: [[: not found
 6: --
./timberborn_linux_bepinex.sh: 63: [[: not found
 7: /home/<me>/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point
./timberborn_linux_bepinex.sh: 63: [[: not found
 8: --verb=waitforexitandrun
./timberborn_linux_bepinex.sh: 63: [[: not found
 9: --
./timberborn_linux_bepinex.sh: 63: [[: not found
 10: /home/<me>/.steam/debian-installation/steamapps/common/Proton - Experimental/proton
./timberborn_linux_bepinex.sh: 63: [[: not found
 11: waitforexitandrun
./timberborn_linux_bepinex.sh: 63: [[: not found
 12: /home/<me>/.steam/debian-installation/steamapps/common/Timberborn/Timberborn.exe
ERROR: command is not found. Either script didn't get expected arguments or regular expresion in it is wrong. Check the list of args above.
- regular expression was: '\/proton$' (refer to https://regex101.com/)
Terminating.
```

**Comment by aruscher** [comment]
As a quickfix you can modify the first line of the `./timberborn_linux_bepinex.sh` file from: `#!/bin/sh` to `#!/bin/bash`.

**Comment by GinFuyou** [comment]
Why are you running the script in the first place? As the top of readme says it should not be needed anymore - your just add dll and then bepinex loads.

**Comment by GinFuyou** [comment]
> As a quickfix you can modify the first line of the `./timberborn_linux_bepinex.sh` file from: `#!/bin/sh` to `#!/bin/bash`.

I guess I've introduced bash syntax there and `sh` won't work anymore? I guess we could just use it as "fix" since I'm not sure if script is useful anymore and most distribution will have bash anyway

**Comment by aruscher** [comment]
yeah go for it...still the whole BepInEx mumbo jumbo is not working. Have you tried your instructions with the recent BepInEx and Timberborn releases? For me, it seems that the whole stuff leading to `exec "$cmd" $@` comes not at the right place since the code for injecting the doorstop libs comes afterward (LD_LIBRARY_PATH, LD_PRELOAD).

-----
EDIT: Sry didn't see your 2nd last post. Seems to work right now.

**Comment by GinFuyou** [comment]
Yes, I don't think there is any need to inject anything. Initially script case for Steam just appears to remove some launch arguments and I've assumed they've just skipped some Steam wrappers that were getting in the way, I've just made changes so arguments are discarded in more "clever" way. Not sure what changed and where but for some time now it launches just as is. No idea about non-steam versions of the game.

**Comment by MarkKocherovsky** [comment]
I've tried without the script in the launch instructions, ~~I also might have put the cart before the horse~~ and it was just loading the base game. I'll try @aruscher's workaround once I get the chance though.

**Comment by aruscher** [comment]
@MarkKocherovsky Before you start messing with the script again, you should check whether a log file was created in your BepInEx directory, since you don't get a console under Linux.

**Comment by MarkKocherovsky** [comment]
@aruscher I've got no log file, and I've tried the bash workaround, but I've still not got the mod manager option in the main menu. I made a plugins directory independently and put the necessary files there as normal.

**Comment by aruscher** [comment]
@MarkKocherovsky when everything works fine, the plugin directory will be created automatically and a log file should appear.
Do you have the `winhttp.dll` in your directory and have you configured the DLL override in protontricks for `winhttp`?

**Comment by MarkKocherovsky** [comment]
I do not, but I did the protontricks directions as written

![image](https://github.com/GinFuyou/Timberborn-GinFuyou/assets/67556945/8e940901-dc20-4f4a-97d8-e3190bf13759)

**Comment by GinFuyou** [comment]
> I do not, but I did the protontricks directions as written
> 
> ![image](https://user-images.githubusercontent.com/67556945/274422813-8e940901-dc20-4f4a-97d8-e3190bf13759.png)

Where are doorstop files? They are the key that makes DLL injection in Unity games as far as I understand.

That's how content of latest BepinEx for Timberborn archieve looks like, all of it (give or take the .sh file) should be in your game root dir.
![Screenshot_20231012_095538](https://github.com/GinFuyou/Timberborn-GinFuyou/assets/75538691/a1100e6d-d12e-4cce-b73a-f347f741c9fa)

Place files there then repeat prontricks winhttp course and try again running game directly from steam without the script.

I'll add screencap of how game root dir looks like for me into the guide I guess, wanted to do it anyway.

**Comment by GinFuyou** [comment]
I've updated script with suggested shebang directive change to use bash and added some clarification and dir screencap to the readme, I wonder if it solves the issue?

**Comment by MarkKocherovsky** [comment]
Alright, this seems to have worked!
