### ISSUE TITLE
Can you add R2modman support to install BepInEx ?

### ISSUE THREAD

**Issue by Enderteck** [GinFuyou/Timberborn-GinFuyou#2]
Should be easier and you still can install custom mods in the instance's mods location

![image](https://github.com/GinFuyou/Timberborn-GinFuyou/assets/123917079/1ee7bbc7-d9ff-424c-aafe-5874274975d6)

**Comment by GinFuyou** [comment]
There are no working mods you can install with it, so I don't see a point

**Comment by Enderteck** [comment]
> There are no working mods you can install with it, so I don't see a point

Yes, there is the only mod you need to add others: BepInEx

That's already one less step of manually installing it.

Mod Manager could also get added there and you could then install everything from r2modman  and in game mod Manager page.

I'm already gonna ask the mod manager's devs to publish on thunderstore.

**Comment by GinFuyou** [comment]
Using another tool is one less step? Sorry but you lost me. Game specifically moved away from thunderstore in favour of mod.io. I don't see how it helps more than add confusion.

**Comment by Enderteck** [comment]
Here are some benefits of bat least adding an option like this to the tutorial.

> You don't have to download anything from your browser,
> You can still launch the vanilla game from Steam or modded with R2ModMan,
> You can install other mods (from mod.io for example)in one instance only by simply clicking browse data folder and pasting the files there:

![image](https://github.com/GinFuyou/Timberborn-GinFuyou/assets/123917079/15d797f6-85db-4df1-bf83-2e52985158ee)

Maybe just adding another option on how to install BepInEx in the tutorial, that should be easy and save time. 
R2Modman is widely used and not saying it's possible to install BepInEx though it is weird.
